"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const RegistrationController_1 = require("../Controlers/RegistrationController");
const GetAllUsersController_1 = require("../Controlers/GetAllUsersController");
const RegistrationController_2 = require("../Controlers/RegistrationController");
const LoginController_1 = require("../Controlers/LoginController");
const GetUserByIdControler_1 = require("../Controlers/GetUserByIdControler");
const ForgetPasswordControler_1 = require("../Controlers/ForgetPasswordControler");
const ChangePasswordControler_1 = require("../Controlers/ChangePasswordControler");
const GetAllProjects_1 = require("../Controlers/GetAllProjects");
const DeleteProjectsControler_1 = require("../Controlers/DeleteProjectsControler");
const UpdateClientController_1 = require("../Controlers/UpdateClientController");
const InsertProjectsController_1 = require("../Controlers/InsertProjectsController");
const GetAllSkillControler_1 = require("../Controlers/GetAllSkillControler");
const AddSkillControler_1 = require("../Controlers/AddSkillControler");
const GetCountry_1 = require("../Controlers/GetCountry");
const getDomainControler_1 = require("../Controlers/getDomainControler");
const AddClientControler_1 = require("../Controlers/AddClientControler");
const GetAllClientControler_1 = require("../Controlers/GetAllClientControler");
const AddProjectControler_1 = require("../Controlers/AddProjectControler");
const UpdateProjectControler_1 = require("../Controlers/UpdateProjectControler");
const DeleteClientControler_1 = require("../Controlers/DeleteClientControler");
const router = express_1.default.Router();
router.post('/register', RegistrationController_1.registrationController);
router.get('/get-register-user', GetAllUsersController_1.getAllUsersController);
router.post('/login', LoginController_1.LoginController);
router.get('/mail-verification/:userId', RegistrationController_2.EmailConfirmationController);
router.get('/get-login-user/:id', GetUserByIdControler_1.getLoginUserByIdController);
router.post('/forget-password', ForgetPasswordControler_1.forgotPasswordController);
router.post('/change-password', ChangePasswordControler_1.changePasswordController);
router.post('/insertProject', InsertProjectsController_1.insertProjectController);
router.get("/get-all-skill", GetAllSkillControler_1.getAllSkillController);
router.post("/add-skill", AddSkillControler_1.addSkillController);
router.get("/get-country", GetCountry_1.getAllCountryControler);
router.get("/get-domain", getDomainControler_1.getDomainControler);
router.post("/add-client", AddClientControler_1.addClientControler);
router.get("/get-all-client", GetAllClientControler_1.getAllClientController);
router.post("/add-projects", AddProjectControler_1.addProjectControler);
router.delete('/delete-project/:id', DeleteProjectsControler_1.deleteClientByIdController);
router.get('/get-allProjects', GetAllProjects_1.getAllProjectsController);
router.put('/update-project/:userId', UpdateProjectControler_1.updateProjectControllerById);
router.delete('/delete-client/:userId', DeleteClientControler_1.deletClient);
router.put('/update-client/:userId', UpdateClientController_1.updateClientController);
exports.default = router;
